---
# ------------------
# Create an AD user:
# ------------------
# 1.) We use the `win_domain_user` module to do the heavy lifting with Active Directory.
# 2.) Ansible uses "{{<insert variable name>}}" as the notation for variable substitution.
# ------------------

- name: Create an Active Directory User
  hosts: all
  gather_facts: false
  tasks:
    - name: Create User Account
      win_domain_user:
        password: "{{onbow_ad_user_pass}}"
        email: "{{onbow_ad_user_samname}}@onbowman.local"
        enabled: yes
        firstname: "{{onbow_ad_user_fname}}"
        surname: "{{onbow_ad_user_lname}}"
        groups: "{{onbow_ad_user_groups}}"
        name: "{{onbow_ad_user_samname}}"
        upn: "{{onbow_ad_user_samname}}@onbowman.local"
        state: present