---
# ---------------------------
# Provisioner Script for IIS:
# ---------------------------

- name: IIS Provisioner Service
  hosts: all
  gather_facts: true
  tasks:
       - name: IIS Feature State
         win_feature:
           name: Web-Server
           state: "{{onbow_iis_desired_state}}"

       - name: IIS Service State
         win_service:
           name: W3Svc
           state: "{{onbow_iis_desired_service_state}}"

       - name: Show Provisioner Results
         debug:
           msg: "IIS on {{ansible_host}} is {{onbow_iis_desired_service_state}}"