---
#-------------------------
# Install IIS to the Host:
#-------------------------
# Use the Win_Feature Module
# to add IIS to the Windows
# Hosts.
#-------------------------

#-------------------------
# No Required Variables.
#-------------------------

- name: Install and Configure IIS
  hosts: all
  gather_facts: false
  tasks:
       - name: install iis
         win_feature:
           name: Web-Server
           state: present

       - name: start iis service
         win_service:
           name: W3Svc
           state: started

       - name: Create website index.html
         win_copy:
           content: "via Ansible - IIS is ready!"
           dest: C:\Inetpub\wwwroot\index.html

       - name: Show website address
         debug:
           msg: "http://{{ ansible_host }}"
