---
#----------------------------------------------------
# Configure Group Policy Settings - [Win_Dsc Module]:
#----------------------------------------------------
# Configure settings for Group Policy in Windows
# Active Directory.
#----------------------------------------------------

#----------------------------------------------------
# Documentation Links
#----------------------------------------------------
# - GroupPolicyDSC: https://github.com/citadelgroup/GroupPolicyDsc
# - Win_Dsc: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html
#----------------------------------------------------

#----------------------------------------------------
# Required Variables:
#----------------------------------------------------
# - dsc_gp_object_name >> <Name of the GPO to modify>
# - dsc_gp_state >> AllSettingsEnabled : UserSettingsDisabled : ComputerSettingsDisabled : AllSettingsDisabled
# - dsc_dp_ensure >> Present : Absent
#----------------------------------------------------

- name: Configure Group Policy Settings
  hosts: all
  tasks:
    - name: Set Group Policy Settings
      win_dsc:
        resource_name: GroupPolicy
        name: "{{dsc_gp_object_name}}"
        ensure: "{{dsc_gp_ensure}}"
        status: "{{dsc_gp_state}}"
