---
#----------------------------------------------------
# Configure Group Policy Settings - [Win_Dsc Module]:
#----------------------------------------------------
# Configure settings for Group Policy in Windows
# Active Directory.
#----------------------------------------------------

#----------------------------------------------------
# Documentation Links
#----------------------------------------------------
# - GroupPolicyDSC: https://github.com/citadelgroup/GroupPolicyDsc
# - Win_Dsc: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html
#----------------------------------------------------

#----------------------------------------------------
# Required Variables:
#----------------------------------------------------
# - dsc_gp__name >> Name of the GPO to modify
# - dsc_gp_key >> Name of the Key / Path / Setting to modify 
# - dsc_gp_object_valuename >> Value Name of the Setting
# - dsc_gp_object_valuedata >> Data for the Setting
# - dsc_gp_object_valuetype >> DWORD : Other
# - dsc_gp_object_ensure >> AllSettingsEnabled : UserSettingsDisabled : ComputerSettingsDisabled : AllSettingsDisabled
#----------------------------------------------------

- name: Configure Group Policy Settings
  hosts: all
  tasks:
    - name: Set Group Policy Settings
      win_dsc:
        resource_name: GPRegistryValue
        Name: "{{dsc_gp_name}}"
        Key: "{{dsc_gp_object_key}}"
        ValueName: "{{dsc_gp_object_valuename}}"
        ValueData: "{{dsc_gp_object_valuedata}}"
        ValueType: "{{dsc_gp_object_valuetype}}"
        Ensure: "{{dsc_gp_object_ensure}}"
