---
#--------------------------------------------
# Setup / Configuration - [Win_Shell Module]:
#--------------------------------------------
# Use the *Win_Shell* Module to execute PS
# commands to validate the the host is ready
# to execute Windows DSC commands.
#
# Example Script comes from Ansible Docs
# below.
#--------------------------------------------

#--------------------------------------------
# Documentation Links:
#--------------------------------------------
# - Win_Shell: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_shell_module.html
# - Win-Dsc: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html
#--------------------------------------------

#--------------------------------------------
# No Required Variables.
#--------------------------------------------

- name: Verify the WSMan HTTP listener is active and configured correctly
  hosts: all
    - tasks:
        ansible.windows.win_shell: |
          $port = (Get-Item -LiteralPath WSMan:\localhost\Client\DefaultPorts\HTTP).Value
          $onlinePorts = @(Get-ChildItem -LiteralPath WSMan:\localhost\Listener |
              Where-Object { 'Transport=HTTP' -in $_.Keys } |
              Get-ChildItem |
              Where-Object Name -eq Port |
              Select-Object -ExpandProperty Value)

          if ($port -notin $onlinePorts) {
              "The default client port $port is not set up as a WSMan HTTP listener, win_dsc will not work."
          }
