---
#-----------------
# Firewall Config:
#-----------------

- name: Firewall Configuration for Windows Hosts.
  hosts: all
  tasks:
  
    - name: Firewall rule to allow SMTP on TCP port 25
      community.windows.win_firewall_rule:
        name: SMTP
        localport: 25
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Firewall rule to allow RDP on TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        profiles: private
        state: present
        enabled: yes

    - name: Firewall rule to allow ICMP v4 echo (ping)
      community.windows.win_firewall_rule:
        name: ICMP Allow incoming V4 echo request
        enabled: yes
        state: present
        profiles: private
        action: allow
        direction: in
        protocol: icmpv4
        icmp_type_code:
        - '8:*'