---
#------------------------------------------------------------------------
# Uninstall Applications / Packages on Windows - [Win_Chocolatey Module]:
#------------------------------------------------------------------------
# Iterate through a list of applications or packages to install on the
# Windows Hosts.
#------------------------------------------------------------------------

#------------------------------------------------------------------------
# Documentation Links:
#------------------------------------------------------------------------
# - Win_Chocolatey: https://docs.ansible.com/ansible/latest/collections/chocolatey/chocolatey/win_chocolatey_module.html
#------------------------------------------------------------------------

#------------------------------------------------------------------------
# Required Variables:
#------------------------------------------------------------------------
# - choco_packages >> List of Packages for Chocolatey to uninstall
# - choco_async >> false: Sequential / Sync | true: Any / Async
#------------------------------------------------------------------------

- name: Use Chocolatey to uninstall applications on the target hosts
  hosts: all
  tasks:

    - name: Uninstall Packages Sync
      win_chocolatey:
        name: '{{ item }}'
        state: absent
      loop: '{{ choco_packages }}'
      when: choco_async == 'false'

    - name: Uninstall Packages Async
      win_chocolatey:
        name: '{{ choco_packages }}'
        state: absent
      when: choco_async == 'true'

# Examples: choco_packages
#  - procexp
#  - putty
#  - windirstat

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows