---
#------------------------------
# Deploy an ASP.NET app to IIS:
#------------------------------

- name: Deploy ASP.NET app to IIS
  hosts: all
  gather_facts: false
  tasks:

    - name: Create directory structure
      win_file:
        path: "C:\\inetpub\\{{onbow_dev_site_name}}"
        state: directory

    - name: Configure IIS site
      win_iis_website:
        name: "{{onbow_dev_site_name}}"
        state: started
        port: 80
        ip: 0.0.0.0
        hostname: "{{onbow_dev_site_name}}.onbowman.com"
        application_pool: "{{onbow_dev_site_name}}"
        physical_path: "c:\\inetpub\\{{onbow_dev_site_name}}"
        parameters: logfile.directory:c:\sites\logs
      register: website

    - name: MS Deploy ASP.NET Site
      win_command: "C:\\{{onbow_dev_site_name}}\\Deployments\\{{onbow_dev_app_name}}\\{{onbow_dev_app_name}}.deploy.cmd /Y"