---
#------------------------------
# Deploy an ASP.NET app to IIS:
#------------------------------
# Uses the IIS Dev Tools + Web
# Publish package to create new
# IIS Sites.
#------------------------------

#------------------------------
# Required Variables:
# - dev_site_name
# - dev_app_name
#------------------------------

- name: Deploy ASP.NET app to IIS
  hosts: all
  gather_facts: false
  tasks:

    - name: Create directory structure
      win_file:
        path: "C:\\inetpub\\{{dev_site_name}}"
        state: directory

    - name: Configure IIS site
      win_iis_website:
        name: "{{dev_site_name}}"
        state: started
        port: 80
        ip: 0.0.0.0
        hostname: "host1.onbowman.com"
        application_pool: "{{dev_site_name}}"
        physical_path: "c:\\inetpub\\{{dev_site_name}}"
        parameters: logfile.directory:c:\sites\logs
      register: website

    - name: MS Deploy ASP.NET Site
      win_command: "C:\\{{dev_site_name}}\\Deployments\\{{dev_app_name}}\\{{dev_app_name}}.deploy.cmd /Y"
