---
#--------------------------------------------------
# Windows DSC - Configure Registry Settings / Keys:
#--------------------------------------------------

- name: Configure Registry Settings via DSC
  hosts: all
    - tasks:
      - name: Use win_dsc module to work with the Win Registry
        win_dsc:
          resoure_name: Registry
          Ensure: Present
          Key: "{{dsc_reg_key}}"
          ValueName: "{{dsc_reg_valuename}}"
          ValueData: "{{dsc_reg_valuedata}}"
          PsDscRunAsCredential_username: '{{ansible_user}}'
          PsDscRunAsCredential_password: '{{ansible_password}}'
        no_log: true