---

# Variables:
# - ad_domain_name
# - ad_domain_recovery_password

- name: Promote Windows Server to Domain Controller
  hosts: all
  tasks:
    - name: Promote the Domain Controller
      ansible.windows.win_domain:
        install_dns: yes
        dns_domain_name: "{{ad_domain_name}}"
        safe_mode_password: "{{ad_domain_recovery_password}}"
