---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Computer Status for Defender
  hosts: all
  tasks:
    - name: Get Defender Status on Machine
      ansible.windows.win_powershell:
        script: |
          Get-MpComputerStatus | ConvertTo-Json | Out-File -FilePath "C:\temp\ansible\win-def-logs.log" -Append -Encoding string
      register: def_status
      
    - name: Status
      ansible.builtin.debug:
        msg: "Current Status: {{ def_status }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
