---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Defender Threat History
  hosts: all
  tasks:
    - name: Get Defender Threat History
      ansible.windows.win_powershell:
        script: |
          Get-MpThreat
        register: machine_threats
    - name: Threats
      ansible.builtin.debug:
        msg: "Current Threats: {{ machine_threats }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
