---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - def_config => JSON configuration for Endpoint
#--------------------------------------------------------------

- name: Set Defender Configuration
  hosts: all
  tasks:
    - name: Set Defender Preferences
      ansible.windows.win_powershell:
        script: |
          $desiredConfig = "{{ def_config }}" | ConvertTo-Json
          $currentConfig = Get-MpPreference | ConvertTo-Json

          if ($desiredConfig -ne $currentConfig)
          {
            "Configuration wasn't current - Updated Defender Preferences." | Out-File -FilePath "C:\temp\ansible\win-def-logs.log" -Append -Encoding string
            $Ansible.Changed = $true
          }
      register: def_result

    - name: Result
      ansible.builtin.debug:
        msg: "Result: {{ def_result }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
