---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - def_results => Picks up results from workflow
# Get-Content -Path "C:\temp\ansible\win-def-logs.log"
#--------------------------------------------------------------

- name: Defender Endpoint Report
  hosts: all
  tasks:
    - name: Gather Logs
      ansible.windows.win_powershell:
        script: |
          cat "C:\temp\ansible\win-def-logs.log"
      register: def_logs

    - name: Clean Up Temp Files
      ansible.windows.win_file:
        path: 'C:\temp\ansible\win-def-logs.log'
        state: absent

    - name: Defender Endpoint Report
      ansible.builtin.debug:
        msg: "Endpoint Report: {{ def_logs }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
