---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - def_config
#--------------------------------------------------------------

- name: Set Defender Configuration
  hosts: all
  tasks:
    - name: Set Defender Preferences as $def_preferences
      ansible.windows.win_powershell:
        script: |
          $def_preferences = Get-MpPreference

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
