---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Firewall Rule for Specific Use Cases
  hosts: all
  tasks:
    - name: Get Defender Preferences as $def_preferences
      ansible.windows.win_powershell:
        script: |
          Get-MpPreference
      register: def_settings
      
    - name: Threats
      ansible.builtin.debug:
        msg: "Current Threats: {{ def_settings.output }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
