---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - def_results => Picks up results from workflow
#--------------------------------------------------------------

- name: Defender Endpoint Report
  hosts: all
  tasks:
    - name: Gather Logs
      ansible.windows.win_powershell:
        script: |
          Get-Content -Path $tempFile
    - name: Defender Endpoint Report
      ansible.builtin.debug:
        msg: "Result: {{ ansible_facts }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
