---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Defender Threat Scan
  hosts: all
  tasks:
    - name: Get Defender Active and Past Threats
      ansible.windows.win_powershell:
        script: |
          $tempFile = "C:\temp\ansible\win-def-logs.log"
          $threats = Get-MpThreatDetection | ConvertTo-Json
          
          if ($threats -eq $null)
          {
            "No Threats Found - All Clear!" | Out-File -FilePath $tempFile -Append -Encoding string
          {
          else
          {
            "Threats Detected!" | Out-File -FilePath $tempFile -Append -Encoding string
            $Ansible.Failed = $true
          }
      ignore_errors: yes
      register: def_results

    - name: Threats
      ansible.builtin.debug:
        msg: "Current Threats: {{ def_results }}"
      ignore_errors: yes

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
