---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Defender Endpoint Report
  hosts: all
  tasks:
    - name: Create Log
      ansible.windows.win_file:
        path: 'C:\temp\ansible\win-def-logs.log'
        state: touch

    - name: Output
      ansible.builtin.debug:
        msg: "Defender Logs have been created!"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
