---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Get Defender Configuration
  hosts: all
  tasks:
    - name: Get Defender Preferences
      ansible.windows.win_powershell:
        script: |
          Get-MpPreference | ConvertTo-Json | Out-File -FilePath "$ENV:Temp\ansible\win-def-logs" -Append -Encoding string
      register: def_settings
      
    - name: Current Preferences
      ansible.builtin.debug:
        msg: "Current Preferences: {{ def_settings }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
