---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - def_results => Picks up results from workflow
#--------------------------------------------------------------

- name: Defender Endpoint Report
  hosts: all
  tasks:
    - name: Create Log
      ansible.windows.win_file:
        path: "%TEMP%\ansible\win-def-logs"
        state: touch

    - name: Output
      ansible.builtin.debug:
        msg: "Defender Logs have been created!"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
