---
#--------------------------------------------------------------
# Get Windows Defender Prefernces - [Win_Powershell Module]:
#--------------------------------------------------------------
# Get Windows Defender Preferences in a Powershell Variable.
#--------------------------------------------------------------

#--------------------------------------------------------------
# Required Variables:
#--------------------------------------------------------------
# - N/A
#--------------------------------------------------------------

- name: Computer Status for Defender
  hosts: all
  tasks:
    - name: Get Defender Status on Machine
      ansible.windows.win_powershell:
        script: |
          Get-MpComputerStatus
      register: machine_status
      
    - name: Threats
      ansible.builtin.debug:
        msg: "Current Threats: {{ machine_status }}"

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
