---
#------------------------------------------------------------
# Remove IIS from Host - [Win_Feature & Win_Service Modules]:
#------------------------------------------------------------
# Use *Win_Service* Module to stop IIS First.
# Use *Win_Feature* module to remove IIS.
# Use *Ansible Msg* to notify details of the play.
#------------------------------------------------------------

#------------------------------------------------------------
# Documentation Links:
#------------------------------------------------------------
# - Win_Feature: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_feature_module.html
# - Win_Service: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html
# - Ansible Msg: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
#------------------------------------------------------------

#------------------------------------------------------------
# No Required Variables
#------------------------------------------------------------

- name: Remove IIS
  hosts: all
  gather_facts: false
  tasks:
       - name: Stop iis service
         win_service:
           name: W3Svc
           state: stopped

       - name: remove iis
         win_feature:
           name: Web-Server
           state: absent

       - name: Report Details
         debug:
           msg: "http://{{ ansible_host }} >> is no longer a serving webhost."
