---
#------------------------------------------------
# Get DataCenter Info - [VMware_Guest Module]:
#------------------------------------------------
- name: Datacenter Data Info
  hosts: all
  tasks:
    - name: Obtain vCenter DataCenter Info
      vmware.vmware_rest.vcenter_datacenter_info:
        vcenter_password: "{{vc_password}}"
        vcenter_username: "{{vc_user}}"
        vcenter_hostname: "{{vc_hostname}}"
      register: datacenterdata
