---
# ------------------------
# Add AD Users to a Group:
# ------------------------

- name: Add Active Directory Groups to a User
  hosts: all
  gather_facts: false
  tasks:
    - name: Add a domain user/group to a domain group
      win_domain_group_membership:
        name: "{{onbow_ad_group_name}}"
        members:
          - "{{onbow_ad_group_members}}"
        state: present