---
# ------------------------
# Add AD Users to a Group:
# ------------------------
# Adds Users to a series
# of Groups in Win AD.
# ------------------------

#-------------------------
# Required Variables:
# - ad_group_names
# - ad_group_members
#-------------------------

- name: Add Active Directory Groups to a User
  hosts: all
  gather_facts: false
  tasks:
    - name: Add a domain user/group to a domain group
      win_domain_group_membership:
        name: "{{item}}"
        members:
          - "{{ad_group_members}}"
        state: present
      - loop:
        - "{{ad_group_names}}"
