---
#------------------------------------------------
# Install Windows Updates - [Win_Updates Module]:
#------------------------------------------------
# Simple example that instructs the Windows Host
# to Install the latest updates from the Server's
# configured *Update Service*.
#
# Example Details: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_updates_module.html
#------------------------------------------------

#------------------------------------------------
# No Required Variables.
#------------------------------------------------

- name: Windows Patching 
  hosts: all
  tasks:
    - name: Install Windows Updates
      win_updates:
        reboot: yes

# https://console.redhat.com/ansible/automation-hub/repo/published/ansible/windows
